### PR TITLE
verify images are not corrupt after reset (fixes #273)

### LINKED ISSUE #273: [BUG] Resulting images broken during repo reset
I don't know what exactly happened but the resulting images got completely broken in ansible/ansible-lint repo.

Context:
* https://github.com/ansible/ansible-lint/pull/416
* https://github.com/ansible/ansible-lint/issues/435
* https://github.com/ansible/ansible-lint/pull/437

Maybe you could figure out what was that from logs or so.

### PR DESCRIPTION
**Pull request by dabutvin**

### CODE REVIEW

**Comment by dabutvin** [comment]
thanks @dlemstra! updated.

File: CompressImagesFunction/CompressImages.cs [hunk 1]
```diff
@@ -119,6 +117,21 @@ public static bool Run(CompressimagesParameters parameters, ILogger logger)
...
+            // verify images are not corrupted by reading from git
+            // see https://github.com/dabutvin/ImgBot/issues/273
+            try
+            {
+                foreach (var image in optimizedImages)
+                {
+                    new MagickImage(image.OriginalPath).Dispose();
+                }
+            }
+            catch (MagickCorruptImageErrorException)
```
Comment (dlemstra) [inline CompressImagesFunction/CompressImages.cs]: You might want to catch `MagickErrorException` instead to make sure you catch all errors.
